src/Entity/User.php
<?php

namespace App\Entity;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Authentication\UserRepository")
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank()
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deleted;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $is_super;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Cluster", inversedBy="users")
     */
    private $clusters;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PasswordRecovery", mappedBy="user", orphanRemoval=true)
     */
    private $passwordRecoveries;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profilepicture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true))
     */
    private $gender;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ActivationToken;

    /**
     * @ORM\Column(type="boolean")
     */
    private $ActivationCheck;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Playstation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Nintendo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Xbox;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Twitter;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Discord;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Facebook;

    /**
     * @ORM\OneToMany(targetEntity=Posts::class, mappedBy="User", orphanRemoval=true, fetch="EAGER")
     * @ORM\OrderBy({"created" = "DESC"})
     */
    private $posts;



    /**
     * @ORM\OneToMany(targetEntity=Likes::class, mappedBy="User", orphanRemoval=true)
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity=Replies::class, mappedBy="user", orphanRemoval=true)
     */
    private $replies;

    /**
     * @ORM\OneToMany(targetEntity=Friends::class, mappedBy="Recipient", orphanRemoval=true, fetch="EAGER")
     */
    private $recipient;

    /**
     * @ORM\OneToMany(targetEntity=Friends::class, mappedBy="Sender", orphanRemoval=true, fetch="EAGER")
     */
    private $sender;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    /**
     * @ORM\OneToMany(targetEntity=Chats::class, mappedBy="User1")
     */
    private $chats;



    public function __construct()
    {
        $this->created = new DateTime('now');
        $this->updated = new DateTime('now');
        $this->is_super = false;
        $this->clusters = new ArrayCollection();
        $this->passwordRecoveries = new ArrayCollection();
        $this->ActivationCheck = "0";
        $this->posts = new ArrayCollection();
        $this->replies = new ArrayCollection();
        $this->likes = new ArrayCollection();
        $this->recipient = new ArrayCollection();
        $this->sender = new ArrayCollection();
        $this->visible = "1";
        $this->chats = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        if(false == empty($password)) {
            $this->password = $password;
        }

        return $this;
    }

    public function getCreated(): ?DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getDeleted(): ?DateTimeInterface
    {
        return $this->deleted;
    }

    public function setDeleted(?DateTimeInterface $deleted): self
    {
        $this->deleted = $deleted;

        return $this;
    }

    public function getUpdated(): ?DateTimeInterface
    {
        return $this->updated;
    }

    public function setUpdated(DateTimeInterface $updated): self
    {
        $this->updated = $updated;

        return $this;
    }

    public function getIsSuper(): ?bool
    {
        return $this->is_super;
    }

    public function setIsSuper(?bool $is_super): self
    {
        $this->is_super = $is_super;

        return $this;
    }

    /**
     * @return Collection|Cluster[]
     */
    public function getClusters(): Collection
    {
        return $this->clusters;
    }

    public function addCluster(Cluster $cluster): self
    {
        if (!$this->clusters->contains($cluster)) {
            $this->clusters[] = $cluster;
        }

        return $this;
    }

    public function removeCluster(Cluster $cluster): self
    {
        if ($this->clusters->contains($cluster)) {
            $this->clusters->removeElement($cluster);
        }

        return $this;
    }

    /**
     * Returns the roles granted to the user.
     *
     *     public function getRoles()
     *     {
     *         return ['ROLE_USER'];
     *     }
     *
     * Alternatively, the roles might be stored on a ``roles`` property,
     * and populated in any number of different ways when the user object
     * is created.
     *
     * @return (Role|string)[] The user roles
     */
    public function getRoles()
    {
        // We don't use text based roles
        // But because Symfony occupies the name 'Role'
        // We use 'clusters'
        return ['ROLE_USER'];
    }

    /**
     * Returns the salt that was originally used to encode the password.
     *
     * This can return null if the password was not encoded using a salt.
     *
     * @return string|null The salt
     */
    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    /**
     * Returns the username used to authenticate the user.
     *
     * @return string The username
     */
    public function getUsername()
    {
        return $this->getName();
    }

    /**
     * Removes sensitive data from the user.
     *
     * This is important if, at any given point, sensitive information like
     * the plain-text password is stored on this object.
     */
    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }


    /**
     * @return Collection|PasswordRecovery[]
     */
    public function getPasswordRecoveries(): Collection
    {
        return $this->passwordRecoveries;
    }

    public function addPasswordRecovery(PasswordRecovery $passwordRecovery): self
    {
        if (!$this->passwordRecoveries->contains($passwordRecovery)) {
            $this->passwordRecoveries[] = $passwordRecovery;
            $passwordRecovery->setUser($this);
        }

        return $this;
    }

    public function removePasswordRecovery(PasswordRecovery $passwordRecovery): self
    {
        if ($this->passwordRecoveries->contains($passwordRecovery)) {
            $this->passwordRecoveries->removeElement($passwordRecovery);
            // set the owning side to null (unless already changed)
            if ($passwordRecovery->getUser() === $this) {
                $passwordRecovery->setUser(null);
            }
        }

        return $this;
    }
    public function getProfilepicture(): ?string
    {
        return $this->profilepicture;
    }

    public function setProfilepicture(string $Profilepicture): self
    {
        $this->profilepicture = $Profilepicture;

        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBirthday(): ?DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(?DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getActivationToken(): ?string
    {
        return $this->ActivationToken;
    }

    public function setActivationToken(string $ActivationToken): self
    {
        $this->ActivationToken = $ActivationToken;

        return $this;
    }

    public function getActivationCheck(): ?bool
    {
        return $this->ActivationCheck;
    }

    public function setActivationCheck(bool $ActivationCheck): self

src/Form/ProfileType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Image;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Validator\Constraints\NotBlank;

class ProfileType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('email', EmailType::class)
            ->add('gender', ChoiceType::class, [
                'choices'  => [
                    'Male' => 'Male',
                    'Female' => 'Female',
                    'Prefer not to say' => 'Prefer not to say'
                ]])
            ->add('birthday', DateType::class, [
                'widget' => 'choice',
                'years' => range(1950,2015),
            ])
            ->add('profilepicture', FileType::class, [
                'label' => 'Profile picture',

                'mapped' => false,

                'required' => false,

                'constraints' => [
                    new Image([
                        'mimeTypesMessage' => 'Please upload a valid image',
                        'maxWidth' => '1920',
                        'maxHeight' => '1080',
                    ])
                ],
            ])

            ->add('playstation', TextType::class, ['required' => false])
            ->add('nintendo', TextType::class, ['required' => false])
            ->add('xbox', TextType::class, ['required' => false])
            ->add('twitter', TextType::class, ['required' => false])
            ->add('discord', TextType::class, ['required' => false])
            ->add('facebook', TextType::class, ['required' => false])
            ->add('visible', CheckboxType::class, [
                        'label'    => 'Show this entry publicly?',
                        'required' => false])
            ->add('password', PasswordType::class)
            ->add('password_verify', PasswordType::class, [
                'mapped' => false
            ]);



    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/ProfileController.php
<?php


namespace App\Controller;

use App\Form\ProfileType;
use App\Form\UserType;
use App\Entity\User;
use App\Entity\Friends;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class ProfileController extends AbstractController
{
    /**
     * @Route("/profile/{id}", name="profile_show", methods={"GET"})
     * @param User $user
     * @param $friendcheck
     * @return Response
     */
    public function show(User $user): Response
    {
        $loggedInUserId = $this->getUser();
        $userId = $user;
        $requestCheck = $this->getDoctrine()->getRepository(Friends::class)->RequestCheck($userId, $loggedInUserId);

        
        return $this->render('profile/show.html.twig', [
            'user' => $user,
            'requestCheck' => $requestCheck
        ]);
    }

    /**
     * @Route("/edit/{id}", name="profile_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, User $user, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $form = $this->createForm(ProfileType::class, $user);
        $form->handleRequest($request);

        /** @var UploadedFile $profilepicture */
        $profilepicture = $form->get('profilepicture')->getData();
        if ($profilepicture) {
            $originalFilename = pathinfo($profilepicture->getClientOriginalName(), PATHINFO_FILENAME);
            // this is needed to safely include the file name as part of the URL
            $newFilename = bin2hex(openssl_random_pseudo_bytes(16)) . '.' . $profilepicture->guessExtension();

            // Move the file to the directory where profile pictures are stored
            try {
                $profilepicture->move(
                    $this->getParameter('profilepicture_directory'),
                    $newFilename
                );
            } catch (FileException $e) {
                // ... handle exception if something happens during file upload
            }

            // updates the 'Profile picture Filename' property to store the image file name
            // instead of its contents
            $user->setProfilePicture($newFilename);
        }

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            if ($form->get('password')->getData() == $form->get('password_verify')->getData()) {

                $user->setPassword($passwordEncoder->encodePassword($user, $form->get('password')->getData()));
                $token = bin2hex(openssl_random_pseudo_bytes(16));
                $entityManager->persist($user);
                $entityManager->flush();

                return $this->redirectToRoute('home');
            }
        }

        return $this->render('profile/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("friends/accept/{id}", name="friendaccept", methods={"GET"})
     * @param Friends $id
     * @return Response
     */
    public function acceptRequest(Friends $id){
        $entityManager = $this->getDoctrine()->getManager();
        $id->setAcceptCheck(true);
        $id->setVisible(false);
        $entityManager->persist($id);
        $entityManager->flush();
        $this->addFlash("success", "You have accepted this friend request. You can now see your friends posts on the homepage.");
        return $this->redirectToRoute('home', [
        ]);
    }

    /**
     * @Route("friends/decline/{id}", name="frienddecline", methods={"GET"})
     * @param Friends $id
     * @return Response
     */
    public function declineRequest(Friends $id){
        $entityManager = $this->getDoctrine()->getManager();
        $id->setAcceptCheck(false);
        $id->setVisible(false);
        $entityManager->persist($id);
        $entityManager->flush();
        $this->addFlash("success", "You have declined this friend request. That user can no longer send you a friend request.");
        return $this->redirectToRoute('home', [
        ]);
    }

    /**
     * @Route("friends/inbox/", name="friendinbox", methods={"GET"})
     * @param User $user
     * @return Response
     */
    public function showInbox(): Response
    {
        $loggedInUserId = $this->getUser();
        $homeCheck = $this->getDoctrine()->getRepository(Friends::class)->HomeCheck($loggedInUserId);
        return $this->render('profile/inbox.html.twig', [
            'user' => $this->getUser(),
            'homeCheck' => $homeCheck
        ]);
    }


}

templates/profile/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
<button class="btn btn-lg btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Profile{% endblock %}

{% block body %}
    <div class="page-header">
        <h1 style="text-align:center;">Edit profile</h1>
    </div>
    <div class="card" style="">
    <div class="card-body">


{{ include('profile/_form.html.twig', {'button_label': 'Update'}) }}

<br/>

    <a href="{{ path('home') }}">Back to home</a>

<br/> <br/>
    </div>
    </div>
{% endblock %}

templates/profile/inbox.html.twig
{% extends 'base.html.twig' %}

    {% block title %}{{ user.username }}'s Inbox{% endblock %}

{% block body %}

    <div class="page-header">
        <h1 style="text-align:center;"> {{ user.username }}'s inbox </h1>
    </div>

    <div class="card">
    <div class="card-body">
    <p class="card-text">
<table class="table table-bordered mb-0">
    <thead class="thead-light">
    <tr>
        <th>Sender</th>
        <th>Accept/Decline</th>
    </tr>
    </thead>
    <tbody>

    {% for friends in app.user.recipient %}
        {% if app.user.id is same as(friends.recipient.id) %}
            {% if friends.visible == 1 %}
    <tr>
        <td>{{ friends.sender.name }}</td>
        <td>
                <a href="{{ path('friendaccept', {'id': friends.id}) }}">Accept</a>
                <a href="{{ path('frienddecline', {'id': friends.id}) }}">Decline</a>
        </td>
    </tr>
            {% endif %}
        {% endif %}
    {% endfor %}
    </tbody>
</table>
    </div>
    </div> <br/>
    <h1 style="text-align:center;">Chats</h1>

            {% for friend in homeCheck %}
                <div class="card text-center">
                <div class="card-body">
            {% if app.user.id != friend.sender.id %}
                    {{ friend.sender.name }} <br/>
                    <a href="{{ path('chat_show', {'id': friend.sender.id }) }}">Chat</a>
            {% else %}
                    {{ friend.recipient.name }} <br/>
                    <a href="{{ path('chat_show', {'id': friend.recipient.id }) }}">Chat</a>

            {% endif %}
                </div>
                </div>
                <br/>
            {% endfor %}

{% endblock %}

templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ user.name }}'s Profile{% endblock %}

{% block body %}
<br>

    <div class="card" style="">
        <div class="card-body">
            <p class="card-text" style="text-align:center;">
                {% if(user.visible == 1) or (requestCheck) or(user.id == app.user.id) %}
                <img src="{{ asset('images/profilepictures/' ~ user.profilepicture) }}" alt="No profile picture found." style="width: 250px; ">
                <h1 style="text-align:center;">{{ user.firstname }} {{ user.lastname }}</h1>
            {% if app.user.id == user.id %}

                <h4 style="text-align:center;"><a href="{{ path('profile_edit', {'id': user.id}) }}"> Edit profile</a></h4>

            {% endif %}

            
            {% if app.user.id != user.id %}
                {% if not requestCheck %}
                        <td><a href="{{ path('friendrequest', {'id': user.id}) }}">Send Friend Request</a></td>
                {% endif %}
                {% if requestCheck %}
                <h5 style="text-align:center;">
                    Chat with your friend, {{ user.name }} <br/>
                    <a href="{{ path('chat_show', {'id': user.id }) }}">Chat</a>

                </h5>

                {% endif %}
            {% endif %}

        </div>
    </div>
    <br/>
    <div class="card-columns d-flex justify-content-center">
    <div class="card" style="">
        <div class="card-body">

                        <div class="row">
                     <div class="col" style="">
                        <p class="card-text">
                         <table class="table mb-0">
                            <tbody>
                            <tr>
                                <th>Id</th>
                                <td>{{ user.id }}</td>
                            </tr>

                            <tr>
                                <th>Username</th>
                                <td>{{ user.name }}</td>
                            </tr>

                            <tr>
                                <th>E-mail </th>
                                <td>{{ user.email }}</td>
                            </tr>
                            <tr>
                                <th>Gender</th>
                                <td>{{ user.gender }}</td>
                            </tr>
                            <tr>
                                <th>Birthday </th>
                                <td>{{ user.birthday ? user.birthday|date('Y-m-d') : ''  }}</td>
                            </tr>


                            </tbody>
                        </table>
                     </div>
                        </div>
    </div>
    </div>


    <div class="card" style="">
        <div class="card-body">

        <div class="col" style="">
            <p class="card-text">
                    <table class="table mb-0">
                        <tbody>

                        <tr>
                            <th>Playstation ID </th>
                            <td>{{ user.playstation }}</td>
                        </tr>
                        <tr>
                            <th>Nintendo Network ID </th>
                            <td>{{ user.nintendo }}</td>
                        </tr>
                        <tr>
                            <th>X-box Live </th>
                            <td>{{ user.xbox }}</td>
                        </tr>
                        <tr>
                            <th>Twitter </th>
                            <td>{{ user.twitter }}</td>
                        </tr>
                        <tr>
                            <th>Discord </th>
                            <td>{{ user.discord }}</td>
                        </tr>
                        <tr>
                            <th>Facebook </th>
                            <td>{{ user.facebook }}</td>
                        </tr>
                        </tbody>
                    </table>


                </div>
            </div>
    </div>
    </div>




    <h1 style="text-align:center;">{{ user.name }}'s Posts</h1>

    <div class="card">
        <div class="card-body" style="text-align:center;">
            {% if app.user.id == user.id %}

                <td><a href="{{ path('posts_new', {'user_id': user.id}) }}"><p style="text-align:center;">New post</a></td>
            {% endif %}
    <table class="table table-bordered mb-0">
    <thead class="thead-light">
    {% if user.posts is not empty %}
    <tr>
        <th>Text</th>
        <th>Date/Time</th>
        {% if app.user.isSuper == "1" or app.user.id == 'user_id' %}

            <th>Admin actions</th>

        {% endif %}
        <th>Show</th>
    </tr>
    </thead>
    <tbody>
    {% endif %}
    {% for posts in user.posts %}
<tr>
    <td>{{ posts.text }}</td>
    <td>{{ posts.created ? posts.created|date('Y-m-d H:i:s') }}</td>


    {% if (app.user.isSuper == "1") or (app.user.id == 'user_id') %}


        <td><a href="{{ path('posts_edit', {'id': posts.id}) }}">Edit</a></td>

    {% endif %}
    <td><a href="{{  path('posts_show', {'id': posts.id}) }}">Show</a></td>
    {% endfor %}
</tr>
    </tbody>
    </table> <br/>
            <p class="card-text" style="text-align:center;">
    <a href="{{ path('home') }}">Back to home</a>
                {% else %}
                    This user's profile is hidden, so you cannot interact with their profile unless they've sent you a friend request that you've accepted.
                {% endif %}
    </div>
    </div>
    <br/>
    <br/>
{% endblock %}