src/Entity/Chats.php
<?php

namespace App\Entity;

use App\Repository\ChatsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChatsRepository::class)
 */
class Chats
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="chats")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User1;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $User2;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Text;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Created;

    public function __construct(){
        $this->Created = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser1(): ?User
    {
        return $this->User1;
    }

    public function setUser1(?User $User1): self
    {
        $this->User1 = $User1;

        return $this;
    }

    public function getUser2(): ?User
    {
        return $this->User2;
    }

    public function setUser2(?User $User2): self
    {
        $this->User2 = $User2;

        return $this;
    }

    public function getText(): ?string
    {
        return $this->Text;
    }

    public function setText(string $Text): self
    {
        $this->Text = $Text;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->Created;
    }

    public function setCreated(\DateTimeInterface $Created): self
    {
        $this->Created = $Created;

        return $this;
    }
}

src/Entity/Friends.php
<?php

namespace App\Entity;

use App\Repository\FriendsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FriendsRepository::class)
 */
class Friends
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $AcceptCheck;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Visible;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="recipient", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Recipient;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="sender", fetch="EAGER")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Sender;


    public function __construct(){
        $this->AcceptCheck = false;
        $this->Visible = true;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAcceptCheck(): ?bool
    {
        return $this->AcceptCheck;
    }

    public function setAcceptCheck(bool $AcceptCheck): self
    {
        $this->AcceptCheck = $AcceptCheck;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->Visible;
    }

    public function setVisible(bool $Visible): self
    {
        $this->Visible = $Visible;

        return $this;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->Recipient = $recipient;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->Recipient;
    }

    public function getSender(): ?User
    {
        return $this->Sender;
    }

    public function setSender(?User $sender): self
    {
        $this->Sender = $sender;

        return $this;
    }




}

src/Entity/Likes.php
<?php

namespace App\Entity;

use App\Repository\LikesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=LikesRepository::class)
 */
class Likes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Posts::class, inversedBy="likes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Post;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="likes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPost(): ?Posts
    {
        return $this->Post;
    }

    public function setPost(?Posts $post): self
    {
        $this->Post = $post;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

src/Entity/Posts.php
<?php

namespace App\Entity;

use App\Repository\PostsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostsRepository::class)
 *
 */
class Posts
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Text;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;



    /**
     * @ORM\OneToMany(targetEntity=Likes::class, mappedBy="Post", orphanRemoval=true)
     */
    private $likes;

    /**
     * @ORM\OneToMany(targetEntity=Replies::class, mappedBy="post", orphanRemoval=true)
     */
    private $replies;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Link;



    public function __construct(){
        $this->created = new \DateTime('now');
        $this->getUser();
        $this->replies = new ArrayCollection();
        $this->likes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->Text;
    }

    public function setText(string $Text): self
    {
        $this->Text = $Text;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    /**
     * @return Collection|Replies[]
     */
    public function getReplies(): Collection
    {
        return $this->replies;
    }

    public function addReply(Replies $reply): self
    {
        if (!$this->replies->contains($reply)) {
            $this->replies[] = $reply;
            $reply->setPost($this);
        }

        return $this;
    }

    public function removeReply(Replies $reply): self
    {
        if ($this->replies->removeElement($reply)) {
            // set the owning side to null (unless already changed)
            if ($reply->getPost() === $this) {
                $reply->setPost(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Likes[]
     */
    public function getLikes(): Collection
    {
        return $this->likes;
    }

    public function addLike(Likes $like): self
    {
        if (!$this->likes->contains($like)) {
            $this->likes[] = $like;
            $like->setPost($this);
        }

        return $this;
    }

    public function removeLike(Likes $like): self
    {
        if ($this->likes->removeElement($like)) {
            // set the owning side to null (unless already changed)
            if ($like->getPost() === $this) {
                $like->setPost(null);
            }
        }

        return $this;
    }

    public function getLink(): ?string
    {
        return $this->Link;
    }

    public function setLink(string $Link): self
    {
        $this->Link = $Link;

        return $this;
    }



}

src/Controller/FriendController.php
<?php


namespace App\Controller;


use App\Entity\User;
use App\Entity\Posts;
use App\Entity\Friends;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FriendController extends AbstractController
{

    /**
     * @Route("friends", name="friends", methods={"GET"})
     */
    public function index(): Response
    {
        return $this->render('friends/search.html.twig', [

        ]);
    }

    /**
     * @Route("friends/search", name="friendsearch", methods={"GET","POST"})
     * @param Request $request
     * @param $searchvalue
     */
    public function search(Request $request)
    {
        $input = $request->request->get('searchvalue');
        $userresults = $this->getDoctrine()->getRepository(User::class)->findUsersBySearch($input);
        $postresults = $this->getDoctrine()->getRepository(Posts::class)->findPostsBySearch($input);
        return $this->render('friends/show.html.twig', [
            'userresults'=>$userresults,
            'postresults'=>$postresults
        ]);

    }

    /**
     * @Route("friends/request/{id}", name="friendrequest", methods={"GET","POST"})
     * @method("POST")
     * @param User $user
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function request(User $user)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $friends = new friends();
        $friends->setRecipient($user);
        $friends->setSender($this->getUser());
        $entityManager->persist($friends);
        $entityManager->flush();
        $this->addFlash("success", "You have sent them a friend request.");
        return $this->redirectToRoute('home', [
            'user' => $user->getID(),
        ]);
    }


}

templates/friends/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Search Friends{% endblock %}

{% block body %}
        <div class="page-header">
            <h1 style="text-align:center;"> Search users/posts</h1>
        </div> <br/>
    <div class="card">
    <div class="card-body">
    <p class="card-text">


    {% if app.user %}
        <form method="post" action="{{ path('friendsearch') }}">
        <label for="searchvalue">Search users/posts:</label><br>
        <input type="text" id="searchvalue" name="searchvalue"><br><br>
        <input type="submit" value="Search">
    {% endif %}
    </form>

    <br/>

    <a href="{{ path('home') }}">Back to home</a>

    <br/> <br/>
    </div>
    </div>
{% endblock %}

templates/friends/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Your search result{% endblock %}

{% block body %}
    <div class="page-header">
        <h1 style="text-align:center;"> Search results </h1>
    </div> <br/>
    <div class="card" style="width:125%;">
    <div class="card-body">
    <p class="card-text">
        <h4>Users:</h4>
    <table class="table">

        <tr>
            <th>Id</th>
            <th>Username</th>
            <th>Profile picture</th>
            <th>E-mail </th>
            <th>Gender</th>
            <th>Birthday </th>
            <th>Playstation ID </th>
            <th>Nintendo Network ID </th>
            <th>X-box Live </th>
            <th>Twitter </th>
            <th>Discord </th>
            <th>Facebook </th>
            <th>Check profile</th>
        </tr>
        <tbody>
        {% for user in userresults %}
            {% if user.visible == 1 %}
        <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.name }}</td>
                <td><img src="{{ asset('images/profilepictures/' ~ user.profilepicture) }}" alt="No profile picture found." style="max-width: 100px; max-height:100px;"></td>
                <td>{{ user.email }}</td>
                <td>{{ user.gender }}</td>
                <td>{{ user.birthday ? user.birthday|date('Y-m-d') : ''  }}</td>
                <td>{{ user.playstation }}</td>
                <td>{{ user.nintendo }}</td>
                <td>{{ user.xbox }}</td>
                <td>{{ user.twitter }}</td>
                <td>{{ user.discord }}</td>
                <td>{{ user.facebook }}</td>
                <td  style="text-align:center;"><a href="{{ path('profile_show', {'id': user.id}) }}"><i class="fas fa-eye"></i></a></td>
        </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table> <br/>

        <h4>Posts:</h4>
        <table class="table">

            <tr>
                <th>Username</th>
                <th>Text</th>
                <th>Link</th>
                <th>Date/Time</th>
                <th>Check post</th>
            </tr>

            <tbody>
            {% for posts in postresults %}
                {% if posts.user.visible == 1 %}
            <tr>
                <td>{{ posts.user.name }}</td>
                <td>{{ posts.text }}</td>
                <td>
                    {% if posts.link == true %}
                        <iframe width="90%" height="100%"
                                src="{{ posts.link }}">
                        </iframe> <br/>
                    {% endif %}
                </td>
                <td>{{ posts.created ? posts.created|date('Y-m-d H:i:s') }}</td>
                <td> <a href="{{  path('posts_show', {'id': posts.id}) }}"><i class="fas fa-eye"></i></a> </td>
            </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>

    <a href="{{ path('home') }}">Back to home</a>
    </div>
    </div>



{% endblock %}